blank_issues_enabled: true
contact_links:
  - name: Questions & discussions
    url: https://github.com/mori-318/flowimds/discussions
    about: Please use GitHub Discussions for usage questions or general Q&A.
