blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/mori/flowimds/discussions
    about: Please use GitHub Discussions for usage questions or general Q&A.
